<?php
// $Id: local_menu.install,v 1.3 2009/07/21 20:09:00 davereid Exp $

/**
 * Implementation of hook_uninstall().
 */
function local_menu_uninstall() {
  variable_del('local_menu_depth');
  variable_del('lcoal_menu_start');
}

/**
 * Add caching to the block.
 */
function local_menu_update_1() {
  $ret = array();
  $ret[] = update_sql("UPDATE {blocks} SET cache = ". (BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_USER) ." WHERE module = 'local_menu'");
  return $ret;
}
