<?php
/* $Id: rounded_corners.module,v 1.1.4.1 2009/07/24 09:54:53 yhager Exp $ */
// länka till ducemnatation

  function rounded_corners_menu() {
    $items = array();
    $items['admin/settings/rounded_corners'] = array(
      'title' => 'Rounded corners',
      'description' => 'Add Rounded corners to css elements.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('rounded_corners_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
     );
     

    return $items;
  }

  function rounded_corners_settings() {
    $form['rounded_corners_status'] = array(
      '#type' => 'fieldset',
      '#title' => t('Rounded corners status'),
      '#weight' => -10,
      '#description' => (rounded_corners_status() !== false) ? t('The rounded corners javascript file is available.') : t('The rounded corners javascript file is unavailable. Download it from <a href="http://methvin.com/jquery/jquery.corner.js">http://methvin.com/jquery/jquery.corner.js</a> and put inside your %rounded_corners_folder folder.', array('%rounded_corners_folder' => drupal_get_path('module', 'rounded_corners'))),
    );
  
    $form['rounded_corners_all_pages'] = array(
      '#type' => 'textarea',
      '#title' => t('Rounded corners to apply on all pages'),
      '#default_value' => variable_get('rounded_corners_all_pages', ''),
      '#description' => t('Add rounded corners on all pages on all themes. Documentation is available at <a href="http://methvin.com/jquery/jq-corner.html">http://methvin.com/jquery/jq-corner.html</a>. Use the format %example with each selector on a new line.', array('%example' => '$(this).corner("round");')),
    );
  
    return system_settings_form($form);
  }

  function rounded_corners_init($main = 0) {
    $path = rounded_corners_status();
    if ($path !== FALSE) {
      drupal_add_js($path);
      drupal_add_js("$(function(){ // shorthand for $(document).ready() \n". variable_get('rounded_corners_all_pages', NULL) ."\n });", 'inline');     
    }
    return '';
  }

  function rounded_corners_status() {
    $path = drupal_get_path('module', 'rounded_corners') .'/jquery.corner.js';  
    if (!is_file($path)) {
      return FALSE;
    }
    return $path;
  }